### ISSUE TITLE
I have reach the working point of make this project works on Python3 & wxPython4, have someone still interesting?

### ISSUE THREAD

**Issue by starofrainnight** [vkucera/task-coach#1]
@vkucera Hi, Vít Kučera

Recently I starts from your "python3" branch and refactor to make it works on Python3 & wxPython4.

Do you still want to take further on this project? 

Though I like this software, but I don't think I have so much time to get all things done.

My development fork on: [Fork]( https://github.com/starofrainnight/task-coach-ex/tree/python3)

The fork achieved that point that make it just run with a workable GUI, but there tons GUI issues needs to be fix and not works properly. Seems there still have long way to make it as stable as 1.4.6.

Best regards,

**Comment by realcarbonneau** [comment]
@starofrainnight I am maintaining and using it on Debian Linux.  See my post in your project and my repo below.

https://github.com/taskcoach/taskcoach/issues/16

https://github.com/realcarbonneau/taskcoach
